// Dummy creative used to de-risk and demo the editor before AI/DB exist (Phase 1).

import type { CreativeState } from "./types";

export const sampleCreative: CreativeState = {
  canvas: { width: 1080, height: 1080, background: "#0F172A" },
  layers: [
    {
      id: "logo",
      type: "image",
      x: 80,
      y: 72,
      width: 180,
      height: 64,
      rotation: 0,
      src: null,
      objectFit: "contain",
      editable: true,
      bindsTo: "logo",
    },
    {
      id: "headline",
      type: "text",
      x: 80,
      y: 260,
      width: 920,
      height: 280,
      rotation: 0,
      content: "Ship campaigns 2x faster",
      fontFamily: "var(--font-inter), Arial, sans-serif",
      fontSize: 92,
      fontWeight: 800,
      color: "#FFFFFF",
      textAlign: "left",
      lineHeight: 1.05,
      editable: true,
      bindsTo: "headline",
    },
    {
      id: "subheadline",
      type: "text",
      x: 80,
      y: 560,
      width: 840,
      height: 120,
      rotation: 0,
      content: "AI writes the copy. You stay in control of every pixel.",
      fontFamily: "var(--font-inter), Arial, sans-serif",
      fontSize: 36,
      fontWeight: 500,
      color: "#94A3B8",
      textAlign: "left",
      lineHeight: 1.25,
      editable: true,
      bindsTo: "subheadline",
    },
    {
      id: "cta_bg",
      type: "shape",
      shape: "rectangle",
      x: 80,
      y: 880,
      width: 340,
      height: 96,
      radius: 14,
      rotation: 0,
      fill: "#2563EB",
      editable: true,
      bindsTo: "color_primary",
    },
    {
      id: "cta_text",
      type: "text",
      x: 80,
      y: 905,
      width: 340,
      height: 50,
      rotation: 0,
      content: "Start free",
      fontFamily: "var(--font-inter), Arial, sans-serif",
      fontSize: 32,
      fontWeight: 600,
      color: "#FFFFFF",
      textAlign: "center",
      lineHeight: 1.2,
      editable: true,
      bindsTo: "cta",
    },
  ],
};
